'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Microsoft.VisualBasic
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.Specialized
Imports System.ComponentModel.DataAnnotations
Imports System.Configuration
Imports System.Linq
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Web
Imports System.Web.Caching
Imports System.Web.DynamicData
Imports System.Web.Profile
Imports System.Web.Security
Imports System.Web.SessionState
Imports System.Web.UI
Imports System.Web.UI.HtmlControls
Imports System.Web.UI.WebControls
Imports System.Web.UI.WebControls.Expressions
Imports System.Web.UI.WebControls.WebParts
Imports System.Xml.Linq

Namespace ASP
Public Class login_aspx
Inherits Global.System.Web.UI.Page
Implements System.Web.SessionState.IRequiresSessionState
Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
Protected WithEvents lblEmailError As Global.System.Web.UI.WebControls.Label
Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
Protected WithEvents lblPasswordError As Global.System.Web.UI.WebControls.Label
Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button
Protected WithEvents loginForm As Global.System.Web.UI.HtmlControls.HtmlForm
<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
Protected ReadOnly Property Profile() As System.Web.Profile.DefaultProfile
Get
Return CType(Me.Context.Profile,System.Web.Profile.DefaultProfile)
End Get
End Property
<System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
Protected ReadOnly Property ApplicationInstance() As System.Web.HttpApplication
Get
Return CType(Me.Context.ApplicationInstance,System.Web.HttpApplication)
End Get
End Property
Private Overloads Function Bind(ByVal expression As String, ByVal format As String) As String
Return ""
End Function
Private Overloads Function Bind(ByVal expression As String) As String
Return ""
End Function
End Class
End Namespace
